server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vehicle_production
    username: root
    password: 14092001
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    root: warn

